export const products = [
  {
    id: 1,
    title: "Yellow Pail",
    description: "On-demand sand castle construction expertise.",
    url: "#",
    votes: 5,
    submitterAvatarUrl: "images/avatars/daniel.jpg",
    productImageUrl: "images/products/image-aqua.png",
  },
  {
    id: 2,
    title: "Yellow Pail",
    description: "On-demand sand castle construction expertise.",
    url: "#",
    votes: 5,
    submitterAvatarUrl: "images/avatars/daniel.jpg",
    productImageUrl: "images/products/image-aqua.png",
  },
  {
    id: 3,
    title: "Yellow Pail",
    description: "On-demand sand castle construction expertise.",
    url: "#",
    votes: 5,
    submitterAvatarUrl: "images/avatars/daniel.jpg",
    productImageUrl: "images/products/image-aqua.png",
  },
  {
    id: 4,
    title: "Yellow Pail",
    description: "On-demand sand castle construction expertise.",
    url: "#",
    votes: 5,
    submitterAvatarUrl: "images/avatars/daniel.jpg",
    productImageUrl: "images/products/image-aqua.png",
  },
];
